### PR TITLE
Fixed intents firing twice if item is clicked rapidly

### LINKED ISSUE #1621: Multiple posts can be opened if tapped in rapid succession
Tap a post and then tap another one (it is easier if you have two fingers ready). They will both open.

Slide should disallow any other posts to open when a post is being loaded.

### PR DESCRIPTION
**Pull request by Nxt3**
- Also fixes click quickly on a comment before the comment menu has collapse getting funky

Added the class `OnSingleClickListener()`. If multiple clicks happen within the specified amount (`300ms` in this case), they will be ignored.

There is even a `wrap()` function that would allow us to wrap an `OnClickListener()` to become a `OnSingleClickListener()`. I commented it out though, simply because it's easier to change two words in the code for a click listener, than move it out into it's own object. :P 

Fixes #1621

### CODE REVIEW

File: app/src/main/java/me/ccrama/redditslide/util/OnSingleClickListener.java [hunk 1]
```diff
@@ -0,0 +1,55 @@
...
+     * Called when a view has been clicked.
+     *
+     * @param v The view that was clicked.
+     */
+    public abstract void onSingleClick(View v);
+
+    @Override
+    public final void onClick(View v) {
+        final long lastClickTime = mLastClickTime;
+        final long now = System.currentTimeMillis();
```
Comment (seizonsenryaku) [inline app/src/main/java/me/ccrama/redditslide/util/OnSingleClickListener.java]: Avoid using System.currentTimeMillis() for this kinds of things, as it is based on the "wall clock" of the phone. Use a monotonic alternative such as SystemClock.uptimeMillis()
See the "Class Overview" in https://developer.android.com/reference/android/os/SystemClock.html for more details.

Comment (Nxt3) [inline app/src/main/java/me/ccrama/redditslide/util/OnSingleClickListener.java]: @seizonsenryaku Thank you! I had no idea.

**Comment by ccrama** [comment]
Has @seizonsenryaku 's suggestion been implemented @Nxt3 ?

**Comment by Nxt3** [comment]
Yep. Just squashed the commits

**Comment by ccrama** [comment]
Awesome! Thank you
